// <auto-generated />
using System;
using DSP.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DSP.Data.Migrations
{
    [DbContext(typeof(DSPMainDbContext))]
    [Migration("20200530095302_Add_All_Table")]
    partial class Add_All_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DSP.Domain.Models.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.Property<long>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DSP.Domain.Models.DspUsers", b =>
                {
                    b.Property<int>("DspUsersId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Active");

                    b.Property<string>("Approver");

                    b.Property<string>("BranchCode")
                        .IsRequired();

                    b.Property<string>("ContactNo");

                    b.Property<string>("CustomerCode")
                        .IsRequired();

                    b.Property<string>("EmailAddress");

                    b.Property<int?>("LicenseAssignLicensesId");

                    b.Property<string>("LicenseAvailablity");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("SAPBranch")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<string>("VendorCode")
                        .IsRequired();

                    b.Property<int>("VendorCustomerVendorsCustomerId");

                    b.Property<string>("Warehouse")
                        .IsRequired();

                    b.Property<string>("WarehouseCode")
                        .IsRequired();

                    b.HasKey("DspUsersId");

                    b.HasIndex("LicenseAssignLicensesId");

                    b.HasIndex("VendorCustomerVendorsCustomerId");

                    b.ToTable("DspUsers");
                });

            modelBuilder.Entity("DSP.Domain.Models.ITN_INV1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BATCH_NO");

                    b.Property<decimal?>("BaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BaseQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DeletedFlag")
                        .HasMaxLength(2);

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ITN_OINVID");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<decimal?>("Quantity")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SERIAL_NO");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("ITN_OINVID");

                    b.ToTable("ITN_INV1");
                });

            modelBuilder.Entity("DSP.Domain.Models.ITN_OINV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmountReturn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BaseEntry")
                        .HasMaxLength(30);

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(20);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("DeletedFlag")
                        .HasMaxLength(2);

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<string>("DocumentOwner")
                        .HasMaxLength(30);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("InvoiceType")
                        .HasMaxLength(20);

                    b.Property<string>("PANVATNumber")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("Postingdate");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(20);

                    b.Property<string>("Remarks")
                        .HasMaxLength(30);

                    b.Property<string>("Status")
                        .HasMaxLength(20);

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalBeforeDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("ITN_OINV");
                });

            modelBuilder.Entity("DSP.Domain.Models.ITN_OPDN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseEntry")
                        .HasMaxLength(30);

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(20);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DeletedFlag")
                        .HasMaxLength(2);

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<string>("DocumentOwner")
                        .HasMaxLength(30);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime?>("PostingDate");

                    b.Property<DateTime?>("ReceivedDate");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(150);

                    b.Property<string>("Remarks")
                        .HasMaxLength(200);

                    b.Property<string>("Status")
                        .HasMaxLength(20);

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalBeforeDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("VendorCode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("ITN_OPDN");
                });

            modelBuilder.Entity("DSP.Domain.Models.ITN_OPRO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(20);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DeletedFlag")
                        .HasMaxLength(2);

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<string>("DocumentOwner")
                        .HasMaxLength(30);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("PORefNo")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("PostingDate");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(150);

                    b.Property<string>("Remarks")
                        .HasMaxLength(30);

                    b.Property<string>("SORefNo")
                        .HasMaxLength(10);

                    b.Property<string>("Status")
                        .HasMaxLength(20);

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalBeforeDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("VendorCode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("ITN_OPRO");
                });

            modelBuilder.Entity("DSP.Domain.Models.ITN_ORPD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseEntry")
                        .HasMaxLength(30);

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(20);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DeletedFlag")
                        .HasMaxLength(2);

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<string>("DocumentOwner")
                        .HasMaxLength(30);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime?>("PostingDate");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(150);

                    b.Property<string>("Remarks")
                        .HasMaxLength(30);

                    b.Property<string>("Status")
                        .HasMaxLength(20);

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalBeforeDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("VendorCode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("ITN_ORPD");
                });

            modelBuilder.Entity("DSP.Domain.Models.ITN_PDN1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BATCH_NO");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal?>("DamagedQuantity")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeletedFlag")
                        .HasMaxLength(2);

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ITN_OPDNID");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<decimal?>("ReceivedQuantity")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReturnQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SERIAL_NO");

                    b.Property<decimal?>("SoldQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("ITN_OPDNID");

                    b.ToTable("ITN_PDN1");
                });

            modelBuilder.Entity("DSP.Domain.Models.ITN_PRO1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BATCH_NO");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DeletedFlag")
                        .HasMaxLength(2);

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ITN_PROID");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReceivedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SERIAL_NO");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("ITN_PROID");

                    b.ToTable("ITN_PRO1");
                });

            modelBuilder.Entity("DSP.Domain.Models.ITN_RPD1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BATCH_NO");

                    b.Property<decimal?>("BaseLine")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal?>("DamagedQuantity")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeletedFlag")
                        .HasMaxLength(2);

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ITN_ORPDID");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<decimal?>("Quantity")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SERIAL_NO");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("ITN_ORPDID");

                    b.ToTable("ITN_RPD1");
                });

            modelBuilder.Entity("DSP.Domain.Models.Licenses", b =>
                {
                    b.Property<int>("LicensesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("License");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("LicensesId");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("DSP.Domain.Models.VendorsCustomer", b =>
                {
                    b.Property<int>("VendorsCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillToAddress");

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("ContactNumber");

                    b.Property<string>("ContactPerson");

                    b.Property<string>("ContractNo")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("EmailId");

                    b.Property<string>("Group")
                        .IsRequired();

                    b.Property<string>("GroupCode")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PANVAT");

                    b.Property<string>("Reference");

                    b.Property<string>("Remarks");

                    b.Property<string>("ShipToAddress");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("VendorsCustomerId");

                    b.ToTable("VendorCustomer");
                });

            modelBuilder.Entity("DSP.Domain.Models.DspUsers", b =>
                {
                    b.HasOne("DSP.Domain.Models.Licenses", "LicenseAssign")
                        .WithMany()
                        .HasForeignKey("LicenseAssignLicensesId");

                    b.HasOne("DSP.Domain.Models.VendorsCustomer", "VendorCustomer")
                        .WithMany()
                        .HasForeignKey("VendorCustomerVendorsCustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DSP.Domain.Models.ITN_INV1", b =>
                {
                    b.HasOne("DSP.Domain.Models.ITN_OINV", "ITN_OINV")
                        .WithMany("ITN_INV1")
                        .HasForeignKey("ITN_OINVID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DSP.Domain.Models.ITN_PDN1", b =>
                {
                    b.HasOne("DSP.Domain.Models.ITN_OPDN", "ITN_OPDN")
                        .WithMany("ITN_PDN1")
                        .HasForeignKey("ITN_OPDNID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DSP.Domain.Models.ITN_PRO1", b =>
                {
                    b.HasOne("DSP.Domain.Models.ITN_OPRO", "ITN_OPRO")
                        .WithMany("ITN_PRO1")
                        .HasForeignKey("ITN_PROID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DSP.Domain.Models.ITN_RPD1", b =>
                {
                    b.HasOne("DSP.Domain.Models.ITN_ORPD", "ITN_ORPD")
                        .WithMany("ITN_RPD1")
                        .HasForeignKey("ITN_ORPDID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
